echo Updating docfx tool globally...
dotnet tool update -g docfx
if %ERRORLEVEL% neq 0 (
    echo Failed to update docfx. Exiting...
)

echo Installing Node.js using winget...
winget install openjs.nodejs
if %ERRORLEVEL% neq 0 (
    echo Failed to install Node.js. Exiting...
)

echo Serving the docfx site...
start cmd /c "docfx serve ./_site"
if %ERRORLEVEL% neq 0 (
    echo Failed to serve docfx site. Exiting...
)

echo Opening localhost:8080 in your default web browser...
start http://localhost:8080
pause
