### YamlMime:ManagedReference
items:
- uid: ApplicationDevelopmentProject.Data.Repository
  commentId: N:ApplicationDevelopmentProject.Data.Repository
  id: ApplicationDevelopmentProject.Data.Repository
  children:
  - ApplicationDevelopmentProject.Data.Repository.IBooseProgramRepository
  langs:
  - csharp
  - vb
  name: ApplicationDevelopmentProject.Data.Repository
  nameWithType: ApplicationDevelopmentProject.Data.Repository
  fullName: ApplicationDevelopmentProject.Data.Repository
  type: Namespace
  assemblies:
  - BooseWebApp.Server
references:
- uid: ApplicationDevelopmentProject.Data.Repository.IBooseProgramRepository
  commentId: T:ApplicationDevelopmentProject.Data.Repository.IBooseProgramRepository
  parent: ApplicationDevelopmentProject.Data.Repository
  href: ApplicationDevelopmentProject.Data.Repository.IBooseProgramRepository.html
  name: IBooseProgramRepository
  nameWithType: IBooseProgramRepository
  fullName: ApplicationDevelopmentProject.Data.Repository.IBooseProgramRepository
- uid: ApplicationDevelopmentProject.Data.Repository
  commentId: N:ApplicationDevelopmentProject.Data.Repository
  href: ApplicationDevelopmentProject.html
  name: ApplicationDevelopmentProject.Data.Repository
  nameWithType: ApplicationDevelopmentProject.Data.Repository
  fullName: ApplicationDevelopmentProject.Data.Repository
  spec.csharp:
  - uid: ApplicationDevelopmentProject
    name: ApplicationDevelopmentProject
    href: ApplicationDevelopmentProject.html
  - name: .
  - uid: ApplicationDevelopmentProject.Data
    name: Data
    href: ApplicationDevelopmentProject.Data.html
  - name: .
  - uid: ApplicationDevelopmentProject.Data.Repository
    name: Repository
    href: ApplicationDevelopmentProject.Data.Repository.html
  spec.vb:
  - uid: ApplicationDevelopmentProject
    name: ApplicationDevelopmentProject
    href: ApplicationDevelopmentProject.html
  - name: .
  - uid: ApplicationDevelopmentProject.Data
    name: Data
    href: ApplicationDevelopmentProject.Data.html
  - name: .
  - uid: ApplicationDevelopmentProject.Data.Repository
    name: Repository
    href: ApplicationDevelopmentProject.Data.Repository.html
